Feature:
 - head-branch: ['^feature', 'feature']
Hotfix:
 - head-branch: ['^hotfix', 'hotfix']
Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
CICD:
- changed-files:
  - any-glob-to-any-file: '.github/**'
PowerShell:
- changed-files:
  - any-glob-to-any-file: ['scripts/**/*.ps1', 'tests/**/*.ps1']
Shell:
- changed-files:
  - any-glob-to-any-file: 'scripts/**/*.sh'
Packer:
- changed-files:
  - any-glob-to-any-file: ['packer-hcl/**', 'templates/**']
Autounattend:
- changed-files:
  - any-glob-to-any-file: 'autounattend/**'
OpenTofu:
- changed-files:
  - any-glob-to-any-file: 'opentofu/**'

