#!/bin/bash
#===================================================================================
# Script: configure_chronyd_suse.sh
# Description: Configure chrony time synchronization for SUSE/openSUSE
# Author: XOAP Infrastructure Team
# Usage: ./configure_chronyd_suse.sh [--ntp-servers "server1 server2"]
#===================================================================================

set -Eeuo pipefail
IFS=$'\n\t'

# Logging functions
log_info() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] $*"
}

log_warn() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [WARN] $*" >&2
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2
}

# Error handler
error_exit() {
    log_error "Script failed at line $1"
    exit 1
}

trap 'error_exit $LINENO' ERR

# Root check
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Variables
NTP_SERVERS="${NTP_SERVERS:-0.suse.pool.ntp.org 1.suse.pool.ntp.org 2.suse.pool.ntp.org 3.suse.pool.ntp.org}"
TIMEZONE="${TIMEZONE:-UTC}"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --ntp-servers)
            NTP_SERVERS="$2"
            shift 2
            ;;
        --timezone)
            TIMEZONE="$2"
            shift 2
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

log_info "Starting chrony configuration for SUSE..."

# Statistics tracking
START_TIME=$(date +%s)
CONFIGS_APPLIED=0

# Install chrony if not present
if ! command -v chronyd &>/dev/null; then
    log_info "Installing chrony..."
    
    if zypper install -y chrony; then
        log_info "✓ chrony installed"
        ((CONFIGS_APPLIED++))
    else
        log_error "Failed to install chrony"
        exit 1
    fi
else
    log_info "chrony is already installed"
fi

# Stop and disable systemd-timesyncd if present
if systemctl is-active --quiet systemd-timesyncd 2>/dev/null; then
    log_info "Disabling systemd-timesyncd..."
    systemctl stop systemd-timesyncd
    systemctl disable systemd-timesyncd
    log_info "✓ systemd-timesyncd disabled"
    ((CONFIGS_APPLIED++))
fi

# Backup existing configuration
CHRONY_CONF="/etc/chrony.conf"
BACKUP_FILE="${CHRONY_CONF}.backup.$(date +%Y%m%d-%H%M%S)"

if [[ -f "$CHRONY_CONF" ]]; then
    cp "$CHRONY_CONF" "$BACKUP_FILE"
    log_info "Backed up chrony configuration to $BACKUP_FILE"
fi

# Create chrony configuration
log_info "Creating chrony configuration..."

cat > "$CHRONY_CONF" <<EOF
# Chrony configuration for SUSE
# Generated by configure_chronyd_suse.sh

# NTP servers
EOF

# Add NTP servers
for server in $NTP_SERVERS; do
    echo "server $server iburst" >> "$CHRONY_CONF"
    log_info "  Added NTP server: $server"
done

cat >> "$CHRONY_CONF" <<'EOF'

# Use NTP sources from DHCP (optional)
# sourcedir /run/chrony-dhcp

# Record the rate at which the system clock gains/losses time
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC)
rtcsync

# Serve time even if not synchronized to a time source
local stratum 10

# Specify directory for log files
logdir /var/log/chrony

# Select which information is logged
#log measurements statistics tracking

# Allow NTP client access from local network (uncomment if needed)
# allow 192.168.0.0/16
# allow 10.0.0.0/8
# allow 172.16.0.0/12

# Specify the key file for NTP authentication
keyfile /etc/chrony.keys

# Get TAI-UTC offset and leap seconds from the system tz database
leapsectz right/UTC

# Specify the maximum correction allowed per update
maxupdateskew 100.0

# Increase the minimum number of selectable sources required
minsources 2

# Ignore sources that are unreachable
maxdistance 16.0
EOF

log_info "✓ chrony configuration created"
((CONFIGS_APPLIED++))

# Set timezone
log_info "Setting timezone to: $TIMEZONE"

if timedatectl set-timezone "$TIMEZONE" 2>/dev/null; then
    log_info "✓ Timezone set"
    ((CONFIGS_APPLIED++))
else
    log_warn "Failed to set timezone"
fi

# Enable and start chronyd
log_info "Enabling chronyd service..."

systemctl enable chronyd
systemctl restart chronyd

# Wait for chronyd to start
sleep 3

if systemctl is-active --quiet chronyd; then
    log_info "✓ chronyd service is running"
else
    log_error "Failed to start chronyd"
    exit 1
fi

# Verify time synchronization
log_info "Verifying time synchronization..."

if chronyc tracking &>/dev/null; then
    log_info "✓ chrony is tracking time sources"
    
    log_info "Chrony tracking status:"
    chronyc tracking | while IFS= read -r line; do
        log_info "  $line"
    done
else
    log_warn "chrony is not yet synchronized"
fi

# Display NTP sources
log_info "NTP sources:"
chronyc sources | while IFS= read -r line; do
    log_info "  $line"
done

# Display sourcestats
log_info "Source statistics:"
chronyc sourcestats | head -n 10 | while IFS= read -r line; do
    log_info "  $line"
done

# Check system time status
log_info "System time status:"
timedatectl status | while IFS= read -r line; do
    log_info "  $line"
done

# Summary statistics
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

SYNC_STATUS=$(chronyc tracking 2>/dev/null | grep "Leap status" | awk '{print $NF}' || echo "unknown")
STRATUM=$(chronyc tracking 2>/dev/null | grep "Stratum" | awk '{print $NF}' || echo "unknown")

log_info "=============================================="
log_info "Chrony Configuration Summary"
log_info "=============================================="
log_info "Configuration file: $CHRONY_CONF"
log_info "NTP servers configured: $(echo $NTP_SERVERS | wc -w)"
log_info "Timezone: $(timedatectl show -p Timezone --value)"
log_info "Service status: $(systemctl is-active chronyd)"
log_info "Stratum: $STRATUM"
log_info "Sync status: $SYNC_STATUS"
log_info "Configurations applied: $CONFIGS_APPLIED"
log_info "Execution time: ${DURATION}s"
log_info "=============================================="
log_info "Chrony configuration completed!"
log_info ""
log_info "Useful commands:"
log_info "  - Tracking: chronyc tracking"
log_info "  - Sources: chronyc sources"
log_info "  - Activity: chronyc activity"
log_info "  - Manual sync: chronyc makestep"