#!/bin/bash
#===================================================================================
# Script: sysctl_hardening_suse.sh
# Description: Apply kernel parameter hardening for SUSE/openSUSE
# Author: XOAP Infrastructure Team
# Usage: ./sysctl_hardening_suse.sh
#===================================================================================

set -Eeuo pipefail
IFS=$'\n\t'

# Logging functions
log_info() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] $*"
}

log_warn() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [WARN] $*" >&2
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2
}

# Error handler
error_exit() {
    log_error "Script failed at line $1"
    exit 1
}

trap 'error_exit $LINENO' ERR

# Root check
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log_info "Starting sysctl hardening for SUSE..."

# Statistics tracking
START_TIME=$(date +%s)
PARAMETERS_SET=0

# Backup current sysctl configuration
BACKUP_FILE="/etc/sysctl.d/99-hardening-suse.conf.backup.$(date +%Y%m%d-%H%M%S)"
if [[ -f /etc/sysctl.d/99-hardening-suse.conf ]]; then
    cp /etc/sysctl.d/99-hardening-suse.conf "$BACKUP_FILE"
    log_info "Backed up existing configuration to $BACKUP_FILE"
fi

# Create hardening configuration
SYSCTL_CONF="/etc/sysctl.d/99-hardening-suse.conf"

log_info "Creating kernel hardening configuration..."

cat > "$SYSCTL_CONF" <<'EOF'
# Kernel hardening configuration for SUSE
# Generated by sysctl_hardening_suse.sh

# Network Security
# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable IP source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Disable ICMP redirect acceptance
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable secure ICMP redirect acceptance
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0

# Disable ICMP redirect sending
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore ICMP ping requests
net.ipv4.icmp_echo_ignore_all = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable TCP SYN cookies
net.ipv4.tcp_syncookies = 1

# Disable IPv6 if not needed (optional)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# IPv6 Security
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.all.forwarding = 0

# Kernel Security
# Enable ASLR
kernel.randomize_va_space = 2

# Restrict kernel pointer exposure
kernel.kptr_restrict = 2

# Restrict dmesg access
kernel.dmesg_restrict = 1

# Restrict kernel profiling
kernel.perf_event_paranoid = 3

# Disable kernel module loading
# kernel.modules_disabled = 1

# Enable ExecShield
kernel.exec-shield = 1

# Restrict ptrace scope
kernel.yama.ptrace_scope = 1

# Core dump restrictions
fs.suid_dumpable = 0

# Filesystem Security
# Increase inotify watches
fs.inotify.max_user_watches = 524288

# Protect symlinks and hardlinks
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2

# Memory Management
# Reduce swap usage
vm.swappiness = 10

# Increase cache pressure for reclaiming memory
vm.vfs_cache_pressure = 50

# Control overcommit memory
vm.overcommit_memory = 1
vm.overcommit_ratio = 50

# TCP/IP Stack Tuning
# Increase TCP buffer sizes
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864

# Enable TCP window scaling
net.ipv4.tcp_window_scaling = 1

# Increase connection backlog
net.core.netdev_max_backlog = 5000
net.ipv4.tcp_max_syn_backlog = 8192

# TCP keepalive settings
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Enable timestamps
net.ipv4.tcp_timestamps = 1

# Enable selective acknowledgments
net.ipv4.tcp_sack = 1

# Disable TCP slow start after idle
net.ipv4.tcp_slow_start_after_idle = 0
EOF

log_info "✓ Hardening configuration created"
((PARAMETERS_SET++))

# Count parameters
PARAM_COUNT=$(grep -cE "^[a-z]" "$SYSCTL_CONF" || echo "0")
log_info "Configuration contains $PARAM_COUNT parameters"

# Apply sysctl settings
log_info "Applying sysctl settings..."

if sysctl --system &>/tmp/sysctl-apply.log; then
    log_info "✓ Sysctl settings applied successfully"
    ((PARAMETERS_SET++))
else
    log_error "Failed to apply some sysctl settings"
    cat /tmp/sysctl-apply.log | while IFS= read -r line; do
        log_warn "  $line"
    done
fi

# Verify critical settings
log_info "Verifying critical security settings..."

VERIFICATION_PASSED=0
VERIFICATION_FAILED=0

verify_setting() {
    local setting=$1
    local expected=$2
    local actual
    
    actual=$(sysctl -n "$setting" 2>/dev/null || echo "ERROR")
    
    if [[ "$actual" == "$expected" ]]; then
        log_info "  ✓ $setting = $actual"
        ((VERIFICATION_PASSED++))
    else
        log_warn "  ✗ $setting = $actual (expected: $expected)"
        ((VERIFICATION_FAILED++))
    fi
}

verify_setting "net.ipv4.conf.all.rp_filter" "1"
verify_setting "net.ipv4.conf.all.accept_source_route" "0"
verify_setting "net.ipv4.conf.all.accept_redirects" "0"
verify_setting "net.ipv4.tcp_syncookies" "1"
verify_setting "kernel.randomize_va_space" "2"
verify_setting "kernel.dmesg_restrict" "1"
verify_setting "fs.suid_dumpable" "0"
verify_setting "fs.protected_symlinks" "1"

# Summary statistics
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

log_info "=============================================="
log_info "Sysctl Hardening Summary"
log_info "=============================================="
log_info "Configuration file: $SYSCTL_CONF"
log_info "Parameters configured: $PARAM_COUNT"
log_info "Verification passed: $VERIFICATION_PASSED"
log_info "Verification failed: $VERIFICATION_FAILED"
log_info "Execution time: ${DURATION}s"
log_info "=============================================="
log_info "Sysctl hardening completed!"
log_info ""
log_info "To view all settings: sysctl -a"
log_info "To reload settings: sysctl --system"