#!/bin/bash
#===================================================================================
# Script: ssh_hardening_suse.sh
# Description: Harden SSH configuration for SUSE/openSUSE
# Author: XOAP Infrastructure Team
# Usage: ./ssh_hardening_suse.sh
#===================================================================================

set -Eeuo pipefail
IFS=$'\n\t'

# Logging functions
log_info() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] $*"
}

log_warn() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [WARN] $*" >&2
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2
}

# Error handler
error_exit() {
    log_error "Script failed at line $1"
    exit 1
}

trap 'error_exit $LINENO' ERR

# Root check
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log_info "Starting SSH hardening for SUSE..."

# Statistics tracking
START_TIME=$(date +%s)
CONFIGS_MODIFIED=0

# Backup SSH configuration
SSHD_CONFIG="/etc/ssh/sshd_config"
BACKUP_FILE="/etc/ssh/sshd_config.backup.$(date +%Y%m%d-%H%M%S)"

if [[ -f "$SSHD_CONFIG" ]]; then
    cp "$SSHD_CONFIG" "$BACKUP_FILE"
    log_info "Backed up SSH configuration to $BACKUP_FILE"
    ((CONFIGS_MODIFIED++))
else
    log_error "SSH configuration file not found"
    exit 1
fi

# Create hardened SSH configuration
log_info "Creating hardened SSH configuration..."

SSHD_HARDENING="/etc/ssh/sshd_config.d/99-hardening.conf"

# Create directory if it doesn't exist
mkdir -p /etc/ssh/sshd_config.d

cat > "$SSHD_HARDENING" <<'EOF'
# SSH Hardening Configuration for SUSE
# Generated by ssh_hardening_suse.sh

# Protocol and Encryption
Protocol 2
Port 22

# Key Exchange Algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256

# Ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Host Key Algorithms
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no

# Disable unsafe authentication methods
HostbasedAuthentication no
IgnoreRhosts yes
IgnoreUserKnownHosts yes

# Login and Session Settings
LoginGraceTime 30
MaxAuthTries 3
MaxSessions 5
MaxStartups 10:30:60

# Strict mode
StrictModes yes
UsePAM yes

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Disable X11 and TCP forwarding
X11Forwarding no
AllowTcpForwarding no
AllowStreamLocalForwarding no
GatewayPorts no

# Disable agent forwarding
AllowAgentForwarding no

# Disable tunneling
PermitTunnel no

# Client alive settings (keep connections alive)
ClientAliveInterval 300
ClientAliveCountMax 2

# Print MOTD and last log
PrintMotd yes
PrintLastLog yes

# Use kernel sandbox mechanisms
UsePrivilegeSeparation sandbox

# Chroot directory (optional)
# ChrootDirectory none

# Banner
Banner /etc/ssh/ssh_banner

# Allow only specific users/groups (uncomment and modify as needed)
# AllowUsers user1 user2
# AllowGroups sshusers wheel
# DenyUsers root
# DenyGroups noSSH
EOF

log_info "✓ SSH hardening configuration created"
((CONFIGS_MODIFIED++))

# Ensure the main config includes drop-in directory
if ! grep -q "^Include /etc/ssh/sshd_config.d/\*.conf" "$SSHD_CONFIG"; then
    sed -i '1i Include /etc/ssh/sshd_config.d/*.conf' "$SSHD_CONFIG"
    log_info "✓ Enabled sshd_config.d inclusion"
    ((CONFIGS_MODIFIED++))
fi

# Create SSH banner
SSH_BANNER="/etc/ssh/ssh_banner"

cat > "$SSH_BANNER" <<'EOF'
#############################################################################
#                         AUTHORIZED ACCESS ONLY                            #
#############################################################################
# This system is for authorized use only. All activity may be monitored   #
# and logged. Unauthorized access is prohibited and may be subject to      #
# prosecution.                                                              #
#############################################################################
EOF

log_info "✓ SSH banner created"
((CONFIGS_MODIFIED++))

# Set proper permissions
chmod 600 "$SSHD_HARDENING"
chmod 644 "$SSH_BANNER"

log_info "✓ Permissions set correctly"

# Generate new host keys if needed
log_info "Checking SSH host keys..."

if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
    log_info "Generating Ed25519 host key..."
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q
    log_info "✓ Ed25519 host key generated"
    ((CONFIGS_MODIFIED++))
fi

if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
    log_info "Generating RSA 4096 host key..."
    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -q
    log_info "✓ RSA 4096 host key generated"
    ((CONFIGS_MODIFIED++))
fi

# Remove weak host keys
for key_type in dsa ecdsa; do
    if [[ -f "/etc/ssh/ssh_host_${key_type}_key" ]]; then
        log_info "Removing weak $key_type host key..."
        rm -f "/etc/ssh/ssh_host_${key_type}_key" "/etc/ssh/ssh_host_${key_type}_key.pub"
        log_info "✓ Removed $key_type key"
        ((CONFIGS_MODIFIED++))
    fi
done

# Validate SSH configuration
log_info "Validating SSH configuration..."

if sshd -t 2>/tmp/sshd-test.log; then
    log_info "✓ SSH configuration is valid"
else
    log_error "SSH configuration validation failed:"
    cat /tmp/sshd-test.log | while IFS= read -r line; do
        log_error "  $line"
    done
    log_error "Restoring backup configuration..."
    cp "$BACKUP_FILE" "$SSHD_CONFIG"
    exit 1
fi

# Restart SSH service
log_info "Restarting SSH service..."

if systemctl restart sshd; then
    log_info "✓ SSH service restarted successfully"
    ((CONFIGS_MODIFIED++))
else
    log_error "Failed to restart SSH service"
    log_error "Restoring backup configuration..."
    cp "$BACKUP_FILE" "$SSHD_CONFIG"
    systemctl restart sshd
    exit 1
fi

# Verify SSH service status
sleep 2

if systemctl is-active --quiet sshd; then
    log_info "✓ SSH service is running"
else
    log_error "SSH service is not running"
    exit 1
fi

# Display current SSH configuration
log_info "Current SSH configuration summary:"
log_info "  Port: $(sshd -T | grep "^port " | awk '{print $2}')"
log_info "  PermitRootLogin: $(sshd -T | grep "^permitrootlogin " | awk '{print $2}')"
log_info "  PasswordAuthentication: $(sshd -T | grep "^passwordauthentication " | awk '{print $2}')"
log_info "  PubkeyAuthentication: $(sshd -T | grep "^pubkeyauthentication " | awk '{print $2}')"

# Summary statistics
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

log_info "=============================================="
log_info "SSH Hardening Summary"
log_info "=============================================="
log_info "Configuration file: $SSHD_HARDENING"
log_info "Backup file: $BACKUP_FILE"
log_info "Configurations modified: $CONFIGS_MODIFIED"
log_info "Service status: $(systemctl is-active sshd)"
log_info "Execution time: ${DURATION}s"
log_info "=============================================="
log_info "SSH hardening completed!"
log_info ""
log_info "IMPORTANT:"
log_info "  - Root login is now disabled"
log_info "  - Password authentication is disabled"
log_info "  - Ensure SSH keys are configured before logging out"
log_info "  - Test SSH access in a new session before closing this one"