#!/bin/bash
#===================================================================================
# Script: ubuntu-configure_fail2ban.sh
# Description: Configure fail2ban intrusion prevention for Ubuntu
# Author: XOAP Infrastructure Team
# Usage: ./ubuntu-configure_fail2ban.sh
#===================================================================================

set -Eeuo pipefail
IFS=$'\n\t'

# Logging functions
log_info() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] $*"
}

log_warn() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [WARN] $*" >&2
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ERROR] $*" >&2
}

# Error handler
error_exit() {
    log_error "Script failed at line $1"
    exit 1
}

trap 'error_exit $LINENO' ERR

# Root check
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log_info "Starting fail2ban configuration for Ubuntu..."

# Statistics tracking
START_TIME=$(date +%s)
CONFIGS_APPLIED=0

# Update package lists
apt-get update -qq

# Install fail2ban
log_info "Installing fail2ban..."

if ! dpkg -l | grep -q "^ii  fail2ban "; then
    if DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban; then
        log_info "✓ fail2ban installed"
        ((CONFIGS_APPLIED++))
    else
        log_error "Failed to install fail2ban"
        exit 1
    fi
else
    log_info "fail2ban is already installed"
fi

# Get installed version
FAIL2BAN_VERSION=$(fail2ban-client version 2>/dev/null || echo "unknown")
log_info "fail2ban version: $FAIL2BAN_VERSION"

# Backup existing configuration
JAIL_LOCAL="/etc/fail2ban/jail.local"
if [[ -f "$JAIL_LOCAL" ]]; then
    BACKUP_FILE="${JAIL_LOCAL}.backup.$(date +%Y%m%d-%H%M%S)"
    cp "$JAIL_LOCAL" "$BACKUP_FILE"
    log_info "Backed up existing configuration to $BACKUP_FILE"
fi

# Create jail.local configuration
log_info "Creating fail2ban configuration..."

cat > "$JAIL_LOCAL" <<'EOF'
# fail2ban jail.local configuration
# Generated by configure_fail2ban_ubuntu.sh

[DEFAULT]
# Ban settings
bantime = 3600
findtime = 600
maxretry = 5

# Email notifications (configure as needed)
destemail = root@localhost
sendername = Fail2Ban
mta = sendmail
action = %(action_mwl)s

# Whitelist IP addresses (space-separated)
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 3600

[sshd-ddos]
enabled = true
port = ssh
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 10
bantime = 1800

[apache-auth]
enabled = false
port = http,https
filter = apache-auth
logpath = /var/log/apache*/*error.log
maxretry = 6

[apache-badbots]
enabled = false
port = http,https
filter = apache-badbots
logpath = /var/log/apache*/*access.log
maxretry = 2

[apache-noscript]
enabled = false
port = http,https
filter = apache-noscript
logpath = /var/log/apache*/*error.log
maxretry = 6

[apache-overflows]
enabled = false
port = http,https
filter = apache-overflows
logpath = /var/log/apache*/*error.log
maxretry = 2

[nginx-http-auth]
enabled = false
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 6

[nginx-limit-req]
enabled = false
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10

[postfix]
enabled = false
port = smtp,465,submission
filter = postfix
logpath = /var/log/mail.log
maxretry = 5

[postfix-sasl]
enabled = false
port = smtp,465,submission
filter = postfix-sasl
logpath = /var/log/mail.log
maxretry = 5

[dovecot]
enabled = false
port = pop3,pop3s,imap,imaps,submission,465,sieve
filter = dovecot
logpath = /var/log/mail.log
maxretry = 5
EOF

log_info "✓ fail2ban configuration created"
((CONFIGS_APPLIED++))

# Create custom filter for additional SSH hardening
log_info "Creating custom SSH filter..."

cat > /etc/fail2ban/filter.d/sshd-ddos.conf <<'EOF'
# fail2ban filter for SSH DDOS attacks

[Definition]
failregex = ^.*sshd\[.*\]: Did not receive identification string from <HOST>$
            ^.*sshd\[.*\]: Connection closed by <HOST> port \d+ \[preauth\]$
            ^.*sshd\[.*\]: Disconnected from <HOST> port \d+ \[preauth\]$
ignoreregex =
EOF

log_info "✓ Custom SSH filter created"
((CONFIGS_APPLIED++))

# Enable and start fail2ban
log_info "Enabling fail2ban service..."

systemctl enable fail2ban
systemctl restart fail2ban

# Wait for service to start
sleep 2

if systemctl is-active --quiet fail2ban; then
    log_info "✓ fail2ban service is running"
    ((CONFIGS_APPLIED++))
else
    log_error "Failed to start fail2ban service"
    exit 1
fi

# Verify configuration
log_info "Verifying fail2ban configuration..."

if fail2ban-client status &>/dev/null; then
    log_info "✓ fail2ban configuration is valid"
else
    log_error "fail2ban configuration validation failed"
    exit 1
fi

# Display active jails
log_info "Active fail2ban jails:"
fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*://; s/,/\n/g' | while IFS= read -r jail; do
    jail=$(echo "$jail" | xargs)
    if [[ -n "$jail" ]]; then
        log_info "  - $jail"
        fail2ban-client status "$jail" 2>/dev/null | grep "Currently banned" | while IFS= read -r line; do
            log_info "    $line"
        done
    fi
done

# Create systemd service override for better logging
log_info "Configuring fail2ban logging..."

mkdir -p /etc/systemd/system/fail2ban.service.d

cat > /etc/systemd/system/fail2ban.service.d/logging.conf <<'EOF'
[Service]
# Increase verbosity for better debugging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=fail2ban
EOF

systemctl daemon-reload

log_info "✓ Logging configured"
((CONFIGS_APPLIED++))

# Summary statistics
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

ACTIVE_JAILS=$(fail2ban-client status 2>/dev/null | grep "Number of jail:" | grep -oE '[0-9]+' || echo "0")
TOTAL_BANNED=$(fail2ban-client status 2>/dev/null | grep -oE 'Currently banned:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | awk '{sum+=$1} END {print sum}' || echo "0")

log_info "=============================================="
log_info "fail2ban Configuration Summary"
log_info "=============================================="
log_info "fail2ban version: $FAIL2BAN_VERSION"
log_info "Configuration file: $JAIL_LOCAL"
log_info "Active jails: $ACTIVE_JAILS"
log_info "Currently banned IPs: $TOTAL_BANNED"
log_info "Configurations applied: $CONFIGS_APPLIED"
log_info "Service status: $(systemctl is-active fail2ban)"
log_info "Execution time: ${DURATION}s"
log_info "=============================================="
log_info "fail2ban configuration completed!"
log_info ""
log_info "fail2ban commands:"
log_info "  - Status: fail2ban-client status"
log_info "  - Jail status: fail2ban-client status JAIL_NAME"
log_info "  - Unban IP: fail2ban-client set JAIL_NAME unbanip IP_ADDRESS"
log_info "  - Ban IP: fail2ban-client set JAIL_NAME banip IP_ADDRESS"
log_info "  - Reload: systemctl reload fail2ban"